### ISSUE TITLE
could you create an example of bulkinsert & bulkupdate with MS ACCESS database via Dapper with VB.NET 

### ISSUE THREAD

**Issue by kana88** [karenpayneoregon/sql-basics#1]
Dear Mrs Karen Payne,

For This link : https://github.com/karenpayneoregon/sql-basics/tree/master/DapperForAccessDatabase

could you create an example of bulkinsert with MS ACCESS database via Dapper with VB.NET and then reflect into datagridview?

and with filter bindinglist with the extension you created namely  : SortableBindingList in datagridview and bulkupdate  from textbox to database and then reflect into datagridview?

 
One more thing I tried this project link there is a warning in the MS Access database, namely: The database you are trying to open requires a newer version of Microsoft Access

I hope I get a reply from you.

Thanks

kana88

**Comment by karenpayneoregon** [comment]
In regards to bulk operations, do not have time for this. Regarding MS-Access, I used the latest version.
